#!/usr/bin/env bash
# Write .env file for a metagraph node's docker-compose
# Usage: write-node-env.sh <node_num> <node_ip> <node1_ip> <image> <gl0_peer_id> <ml0_peer_id> <cl_password> [token_id]
#
# node_num: 1 = genesis node (IS_INITIAL=true), 2/3 = validators

set -euo pipefail

NODE_NUM="${1:?Usage: write-node-env.sh <node_num> <node_ip> <node1_ip> <image> <gl0_peer_id> <ml0_peer_id> <cl_password> [token_id]}"
NODE_IP="${2:?Node IP required}"
NODE1_IP="${3:?Node1 IP required}"
IMAGE="${4:?Image required}"
GL0_PEER_ID="${5:?GL0 peer ID required}"
ML0_PEER_ID="${6:?ML0 peer ID required}"
CL_PASSWORD="${7:?CL_PASSWORD required}"
TOKEN_ID="${8:-}"

ENV_FILE="/opt/ottochain/.env"

# Node1 = genesis node, others = validators
if [ "$NODE_NUM" = "1" ]; then
  IS_INITIAL="true"
  KEYS_DIR="/opt/ottochain/keys"
else
  IS_INITIAL=""
  KEYS_DIR="/opt/ottochain/keys${NODE_NUM}"
fi

cat > "$ENV_FILE" << EOF
# OttoChain Metagraph Node ${NODE_NUM} Environment
# Auto-generated by deploy workflow - DO NOT EDIT ON SERVER

# Image
IMAGE=${IMAGE}

# Node identity
EXTERNAL_IP=${NODE_IP}
NODE1_IP=${NODE1_IP}
IS_INITIAL=${IS_INITIAL}
KEYS_DIR=${KEYS_DIR}

# Keystore
CL_PASSWORD=${CL_PASSWORD}

# Peer IDs (pre-computed from p12 keystores)
GL0_PEER_ID=${GL0_PEER_ID}
ML0_PEER_ID=${ML0_PEER_ID}

# Metagraph token
TOKEN_ID=${TOKEN_ID}

# JVM tuning (override per-layer if needed)
GL0_JAVA_OPTS=-Xmx3g -Xms2g -XX:+UseZGC -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=256m -XX:ReservedCodeCacheSize=128m -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:SoftRefLRUPolicyMSPerMB=50 -XX:ZUncommitDelay=60 -Dlogback.configurationFile=/ottochain/logback.xml
ML0_JAVA_OPTS=-Xmx4g -Xms2g -XX:+UseZGC -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=256m -XX:ReservedCodeCacheSize=128m -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:SoftRefLRUPolicyMSPerMB=50 -XX:ZUncommitDelay=60 -Dlogback.configurationFile=/ottochain/logback.xml
DL1_JAVA_OPTS=-Xmx3g -Xms1g -XX:+UseZGC -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=256m -XX:ReservedCodeCacheSize=128m -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:SoftRefLRUPolicyMSPerMB=50 -XX:ZUncommitDelay=60 -Dlogback.configurationFile=/ottochain/logback.xml
CL1_JAVA_OPTS=-Xmx2g -Xms1g -XX:+UseZGC -XX:MaxMetaspaceSize=256m -XX:MaxDirectMemorySize=256m -XX:ReservedCodeCacheSize=128m -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:SoftRefLRUPolicyMSPerMB=50 -XX:ZUncommitDelay=60 -Dlogback.configurationFile=/ottochain/logback.xml
EOF

echo "✓ Wrote $ENV_FILE for node${NODE_NUM} (IS_INITIAL=${IS_INITIAL:-false}, KEYS=${KEYS_DIR})"
